[pytest]
markers =
    smoke: smoke test cases
    vertical: vertical test cases
    trading: trading test cases
    retail_ecommerce: retail and ecommerce test cases
    mobile: mobile app development test cases
    ai: ai test cases
    -m
